### ISSUE TITLE
Did all data just get wiped out?

### ISSUE THREAD

**Issue by CasJam** [Leeflets/leeflets#41]
I was making an edit to the Features area (reordering them).  Looked like it took a while to reload after Save.  When it finished, it looked like all data was wiped out from the site, leaving just the barebones design template.

http://cl.ly/image/1n3u1938330j

**Comment by bradt** [comment]
I think this was probably caused by this bug 249c1dcc86926ec785982a69938c3d78d3e767ee, but even so, if something happens and the data to be saved is null or empty, it should not save it to the file. I've added a check for this, so if the data is null or empty, it just won't save: 2262c5734e74cb2ea05bb827bf574971af0fcaff.
