### ISSUE TITLE
Repeatable Field Image Upload Error

### ISSUE THREAD

**Issue by itsdavidmorgan** [Leeflets/leeflets#70]
The image uploader is displaying an error whenever I try to upload an image:

Form field not found (#2).

![Screen Shot 2013-03-29 at 6 11 41 PM](https://f.cloud.github.com/assets/1852322/319866/3bc4453e-98f0-11e2-8382-60dfe6c04b2f.png)

**Comment by hawaiiwp** [comment]
I have the same issue.  Not sure if it might be server related???

**Comment by itsdavidmorgan** [comment]
Are you on a localhost @hawaiiwp?

**Comment by itsdavidmorgan** [comment]
The template API has recently been updated, so I'm assuming this is a symptom of the new API.

**Comment by hawaiiwp** [comment]
No, I'm on a Nodeki.com shared server.  

---

Arlen Nagata
Designing Hawaii's Websites with WordPress
HawaiiWP.com (http://hawaiiwp.com)

808.232.7921 (tel:808.232.7921)

**Comment by itsdavidmorgan** [comment]
Okay, it's probably just an issue of the Koala template needing to be updated with the new API.

**Comment by jptksc** [comment]
I'm experiencing the same on a localhost. I think Brad updated Koala with the new API, but I'll have a look this weekend. Been meaning to make some updates to the Koala template anyway.

**Comment by rossdev** [comment]
I'm seeing the same issue on my VPS

**Comment by bradt** [comment]
Yep, not sure what caused this, but looking into it.

**Comment by rossdev** [comment]
Looks like other unexpected behaviors with the fields too... 
![Capture](https://f.cloud.github.com/assets/871896/320950/274eed82-997e-11e2-8cae-205372900273.PNG)

**Comment by rossdev** [comment]
The above issue is not repeatable but other combinations of fields showing up/going away, with/without text in IE10... looks like it's a caching issue with the browser.

**Comment by ghost** [comment]
I am having the "Form field not found (#2)" error on two different localhosts as well. I'm guessing this is just an issue with localhosts?

**Comment by plgg** [comment]
This error happens after changing the empty-to-show parameter to a lesser value, on any hosts.
Repeatable fields containing an image are limited to the number of "empty-to-show". 
Example: empty-to-show=4
You may add images without errors, but only 4 images get saved. The 4th is overwritten by the last You added.
I found some errors, like passing non-array parameters to array_merge, what doesn't work in PHP 5
This solved some smaller problems, but in that case I had no success.
A pity. Leeflet is a great thing, but I miss any release fixing major bugs and any answer from their support site since 7 weeks.
